import { Yekan } from "@/utils/Fonts";
import "./globals.css";
import Layout from "@/components/layout/Layout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={Yekan.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
