import { Yekan } from "@/utils/Fonts";
import "./globals.css";
import Layout from "@/components/layout/Layout";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};
import { ToastContainer } from "react-toastify";

export default function RootLayout({ children }) {
  return (
    <html lang="fa" dir="rtl">
      <body className={Yekan.className}>
        <ToastContainer />
        <Layout>{children}</Layout>
      </body>
    </html>
  );
}
